// Generated by gencpp from file orbbec_camera/DeviceStatus.msg
// DO NOT EDIT!


#ifndef ORBBEC_CAMERA_MESSAGE_DEVICESTATUS_H
#define ORBBEC_CAMERA_MESSAGE_DEVICESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace orbbec_camera
{
template <class ContainerAllocator>
struct DeviceStatus_
{
  typedef DeviceStatus_<ContainerAllocator> Type;

  DeviceStatus_()
    : header()
    , color_frame_rate_cur(0.0)
    , color_frame_rate_avg(0.0)
    , color_frame_rate_min(0.0)
    , color_frame_rate_max(0.0)
    , color_delay_ms_cur(0.0)
    , color_delay_ms_avg(0.0)
    , color_delay_ms_min(0.0)
    , color_delay_ms_max(0.0)
    , depth_frame_rate_cur(0.0)
    , depth_frame_rate_avg(0.0)
    , depth_frame_rate_min(0.0)
    , depth_frame_rate_max(0.0)
    , depth_delay_ms_cur(0.0)
    , depth_delay_ms_avg(0.0)
    , depth_delay_ms_min(0.0)
    , depth_delay_ms_max(0.0)
    , device_online(false)
    , connection_type()
    , customer_calibration_ready(false)
    , calibration_from_factory(false)
    , calibration_from_launch_param(false)  {
    }
  DeviceStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , color_frame_rate_cur(0.0)
    , color_frame_rate_avg(0.0)
    , color_frame_rate_min(0.0)
    , color_frame_rate_max(0.0)
    , color_delay_ms_cur(0.0)
    , color_delay_ms_avg(0.0)
    , color_delay_ms_min(0.0)
    , color_delay_ms_max(0.0)
    , depth_frame_rate_cur(0.0)
    , depth_frame_rate_avg(0.0)
    , depth_frame_rate_min(0.0)
    , depth_frame_rate_max(0.0)
    , depth_delay_ms_cur(0.0)
    , depth_delay_ms_avg(0.0)
    , depth_delay_ms_min(0.0)
    , depth_delay_ms_max(0.0)
    , device_online(false)
    , connection_type(_alloc)
    , customer_calibration_ready(false)
    , calibration_from_factory(false)
    , calibration_from_launch_param(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _color_frame_rate_cur_type;
  _color_frame_rate_cur_type color_frame_rate_cur;

   typedef double _color_frame_rate_avg_type;
  _color_frame_rate_avg_type color_frame_rate_avg;

   typedef double _color_frame_rate_min_type;
  _color_frame_rate_min_type color_frame_rate_min;

   typedef double _color_frame_rate_max_type;
  _color_frame_rate_max_type color_frame_rate_max;

   typedef double _color_delay_ms_cur_type;
  _color_delay_ms_cur_type color_delay_ms_cur;

   typedef double _color_delay_ms_avg_type;
  _color_delay_ms_avg_type color_delay_ms_avg;

   typedef double _color_delay_ms_min_type;
  _color_delay_ms_min_type color_delay_ms_min;

   typedef double _color_delay_ms_max_type;
  _color_delay_ms_max_type color_delay_ms_max;

   typedef double _depth_frame_rate_cur_type;
  _depth_frame_rate_cur_type depth_frame_rate_cur;

   typedef double _depth_frame_rate_avg_type;
  _depth_frame_rate_avg_type depth_frame_rate_avg;

   typedef double _depth_frame_rate_min_type;
  _depth_frame_rate_min_type depth_frame_rate_min;

   typedef double _depth_frame_rate_max_type;
  _depth_frame_rate_max_type depth_frame_rate_max;

   typedef double _depth_delay_ms_cur_type;
  _depth_delay_ms_cur_type depth_delay_ms_cur;

   typedef double _depth_delay_ms_avg_type;
  _depth_delay_ms_avg_type depth_delay_ms_avg;

   typedef double _depth_delay_ms_min_type;
  _depth_delay_ms_min_type depth_delay_ms_min;

   typedef double _depth_delay_ms_max_type;
  _depth_delay_ms_max_type depth_delay_ms_max;

   typedef uint8_t _device_online_type;
  _device_online_type device_online;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _connection_type_type;
  _connection_type_type connection_type;

   typedef uint8_t _customer_calibration_ready_type;
  _customer_calibration_ready_type customer_calibration_ready;

   typedef uint8_t _calibration_from_factory_type;
  _calibration_from_factory_type calibration_from_factory;

   typedef uint8_t _calibration_from_launch_param_type;
  _calibration_from_launch_param_type calibration_from_launch_param;





  typedef boost::shared_ptr< ::orbbec_camera::DeviceStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orbbec_camera::DeviceStatus_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceStatus_

typedef ::orbbec_camera::DeviceStatus_<std::allocator<void> > DeviceStatus;

typedef boost::shared_ptr< ::orbbec_camera::DeviceStatus > DeviceStatusPtr;
typedef boost::shared_ptr< ::orbbec_camera::DeviceStatus const> DeviceStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orbbec_camera::DeviceStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::orbbec_camera::DeviceStatus_<ContainerAllocator1> & lhs, const ::orbbec_camera::DeviceStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.color_frame_rate_cur == rhs.color_frame_rate_cur &&
    lhs.color_frame_rate_avg == rhs.color_frame_rate_avg &&
    lhs.color_frame_rate_min == rhs.color_frame_rate_min &&
    lhs.color_frame_rate_max == rhs.color_frame_rate_max &&
    lhs.color_delay_ms_cur == rhs.color_delay_ms_cur &&
    lhs.color_delay_ms_avg == rhs.color_delay_ms_avg &&
    lhs.color_delay_ms_min == rhs.color_delay_ms_min &&
    lhs.color_delay_ms_max == rhs.color_delay_ms_max &&
    lhs.depth_frame_rate_cur == rhs.depth_frame_rate_cur &&
    lhs.depth_frame_rate_avg == rhs.depth_frame_rate_avg &&
    lhs.depth_frame_rate_min == rhs.depth_frame_rate_min &&
    lhs.depth_frame_rate_max == rhs.depth_frame_rate_max &&
    lhs.depth_delay_ms_cur == rhs.depth_delay_ms_cur &&
    lhs.depth_delay_ms_avg == rhs.depth_delay_ms_avg &&
    lhs.depth_delay_ms_min == rhs.depth_delay_ms_min &&
    lhs.depth_delay_ms_max == rhs.depth_delay_ms_max &&
    lhs.device_online == rhs.device_online &&
    lhs.connection_type == rhs.connection_type &&
    lhs.customer_calibration_ready == rhs.customer_calibration_ready &&
    lhs.calibration_from_factory == rhs.calibration_from_factory &&
    lhs.calibration_from_launch_param == rhs.calibration_from_launch_param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::orbbec_camera::DeviceStatus_<ContainerAllocator1> & lhs, const ::orbbec_camera::DeviceStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace orbbec_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orbbec_camera::DeviceStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orbbec_camera::DeviceStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orbbec_camera::DeviceStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cf8d5046efc1ba84cc148313b15c5cc";
  }

  static const char* value(const ::orbbec_camera::DeviceStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cf8d5046efc1ba8ULL;
  static const uint64_t static_value2 = 0x4cc148313b15c5ccULL;
};

template<class ContainerAllocator>
struct DataType< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orbbec_camera/DeviceStatus";
  }

  static const char* value(const ::orbbec_camera::DeviceStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# --- Color stream ---\n"
"float64 color_frame_rate_cur\n"
"float64 color_frame_rate_avg\n"
"float64 color_frame_rate_min\n"
"float64 color_frame_rate_max\n"
"\n"
"float64 color_delay_ms_cur\n"
"float64 color_delay_ms_avg\n"
"float64 color_delay_ms_min\n"
"float64 color_delay_ms_max\n"
"\n"
"# --- Depth stream ---\n"
"float64 depth_frame_rate_cur\n"
"float64 depth_frame_rate_avg\n"
"float64 depth_frame_rate_min\n"
"float64 depth_frame_rate_max\n"
"\n"
"float64 depth_delay_ms_cur\n"
"float64 depth_delay_ms_avg\n"
"float64 depth_delay_ms_min\n"
"float64 depth_delay_ms_max\n"
"\n"
"# --- Device info ---\n"
"bool device_online\n"
"string connection_type   # e.g. \"USB2.0\", \"USB3.0\", \"GigE\"\n"
"\n"
"# --- Calibration status ---\n"
"bool customer_calibration_ready\n"
"bool calibration_from_factory\n"
"bool calibration_from_launch_param\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::orbbec_camera::DeviceStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.color_frame_rate_cur);
      stream.next(m.color_frame_rate_avg);
      stream.next(m.color_frame_rate_min);
      stream.next(m.color_frame_rate_max);
      stream.next(m.color_delay_ms_cur);
      stream.next(m.color_delay_ms_avg);
      stream.next(m.color_delay_ms_min);
      stream.next(m.color_delay_ms_max);
      stream.next(m.depth_frame_rate_cur);
      stream.next(m.depth_frame_rate_avg);
      stream.next(m.depth_frame_rate_min);
      stream.next(m.depth_frame_rate_max);
      stream.next(m.depth_delay_ms_cur);
      stream.next(m.depth_delay_ms_avg);
      stream.next(m.depth_delay_ms_min);
      stream.next(m.depth_delay_ms_max);
      stream.next(m.device_online);
      stream.next(m.connection_type);
      stream.next(m.customer_calibration_ready);
      stream.next(m.calibration_from_factory);
      stream.next(m.calibration_from_launch_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orbbec_camera::DeviceStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orbbec_camera::DeviceStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_frame_rate_cur: ";
    Printer<double>::stream(s, indent + "  ", v.color_frame_rate_cur);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_frame_rate_avg: ";
    Printer<double>::stream(s, indent + "  ", v.color_frame_rate_avg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_frame_rate_min: ";
    Printer<double>::stream(s, indent + "  ", v.color_frame_rate_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_frame_rate_max: ";
    Printer<double>::stream(s, indent + "  ", v.color_frame_rate_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_delay_ms_cur: ";
    Printer<double>::stream(s, indent + "  ", v.color_delay_ms_cur);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_delay_ms_avg: ";
    Printer<double>::stream(s, indent + "  ", v.color_delay_ms_avg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_delay_ms_min: ";
    Printer<double>::stream(s, indent + "  ", v.color_delay_ms_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color_delay_ms_max: ";
    Printer<double>::stream(s, indent + "  ", v.color_delay_ms_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_frame_rate_cur: ";
    Printer<double>::stream(s, indent + "  ", v.depth_frame_rate_cur);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_frame_rate_avg: ";
    Printer<double>::stream(s, indent + "  ", v.depth_frame_rate_avg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_frame_rate_min: ";
    Printer<double>::stream(s, indent + "  ", v.depth_frame_rate_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_frame_rate_max: ";
    Printer<double>::stream(s, indent + "  ", v.depth_frame_rate_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_delay_ms_cur: ";
    Printer<double>::stream(s, indent + "  ", v.depth_delay_ms_cur);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_delay_ms_avg: ";
    Printer<double>::stream(s, indent + "  ", v.depth_delay_ms_avg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_delay_ms_min: ";
    Printer<double>::stream(s, indent + "  ", v.depth_delay_ms_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_delay_ms_max: ";
    Printer<double>::stream(s, indent + "  ", v.depth_delay_ms_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_online: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.device_online);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "connection_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.connection_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "customer_calibration_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.customer_calibration_ready);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "calibration_from_factory: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_from_factory);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "calibration_from_launch_param: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_from_launch_param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORBBEC_CAMERA_MESSAGE_DEVICESTATUS_H
