// Generated by gencpp from file orbbec_camera/SetArraysRequest.msg
// DO NOT EDIT!


#ifndef ORBBEC_CAMERA_MESSAGE_SETARRAYSREQUEST_H
#define ORBBEC_CAMERA_MESSAGE_SETARRAYSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace orbbec_camera
{
template <class ContainerAllocator>
struct SetArraysRequest_
{
  typedef SetArraysRequest_<ContainerAllocator> Type;

  SetArraysRequest_()
    : enable(false)
    , data_param()  {
    }
  SetArraysRequest_(const ContainerAllocator& _alloc)
    : enable(false)
    , data_param(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_param_type;
  _data_param_type data_param;





  typedef boost::shared_ptr< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetArraysRequest_

typedef ::orbbec_camera::SetArraysRequest_<std::allocator<void> > SetArraysRequest;

typedef boost::shared_ptr< ::orbbec_camera::SetArraysRequest > SetArraysRequestPtr;
typedef boost::shared_ptr< ::orbbec_camera::SetArraysRequest const> SetArraysRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orbbec_camera::SetArraysRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::orbbec_camera::SetArraysRequest_<ContainerAllocator1> & lhs, const ::orbbec_camera::SetArraysRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable &&
    lhs.data_param == rhs.data_param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::orbbec_camera::SetArraysRequest_<ContainerAllocator1> & lhs, const ::orbbec_camera::SetArraysRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace orbbec_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68c3a0c0d5c3b7f26963654a009c43dd";
  }

  static const char* value(const ::orbbec_camera::SetArraysRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68c3a0c0d5c3b7f2ULL;
  static const uint64_t static_value2 = 0x6963654a009c43ddULL;
};

template<class ContainerAllocator>
struct DataType< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orbbec_camera/SetArraysRequest";
  }

  static const char* value(const ::orbbec_camera::SetArraysRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enable\n"
"float32[] data_param\n"
;
  }

  static const char* value(const ::orbbec_camera::SetArraysRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
      stream.next(m.data_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetArraysRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orbbec_camera::SetArraysRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orbbec_camera::SetArraysRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data_param: ";
    if (v.data_param.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data_param.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.data_param[i]);
    }
    if (v.data_param.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORBBEC_CAMERA_MESSAGE_SETARRAYSREQUEST_H
