// Generated by gencpp from file orbbec_camera/SetFilterRequest.msg
// DO NOT EDIT!


#ifndef ORBBEC_CAMERA_MESSAGE_SETFILTERREQUEST_H
#define ORBBEC_CAMERA_MESSAGE_SETFILTERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace orbbec_camera
{
template <class ContainerAllocator>
struct SetFilterRequest_
{
  typedef SetFilterRequest_<ContainerAllocator> Type;

  SetFilterRequest_()
    : filter_name()
    , filter_enable(false)
    , filter_param()  {
    }
  SetFilterRequest_(const ContainerAllocator& _alloc)
    : filter_name(_alloc)
    , filter_enable(false)
    , filter_param(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _filter_name_type;
  _filter_name_type filter_name;

   typedef uint8_t _filter_enable_type;
  _filter_enable_type filter_enable;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _filter_param_type;
  _filter_param_type filter_param;





  typedef boost::shared_ptr< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFilterRequest_

typedef ::orbbec_camera::SetFilterRequest_<std::allocator<void> > SetFilterRequest;

typedef boost::shared_ptr< ::orbbec_camera::SetFilterRequest > SetFilterRequestPtr;
typedef boost::shared_ptr< ::orbbec_camera::SetFilterRequest const> SetFilterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orbbec_camera::SetFilterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::orbbec_camera::SetFilterRequest_<ContainerAllocator1> & lhs, const ::orbbec_camera::SetFilterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filter_name == rhs.filter_name &&
    lhs.filter_enable == rhs.filter_enable &&
    lhs.filter_param == rhs.filter_param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::orbbec_camera::SetFilterRequest_<ContainerAllocator1> & lhs, const ::orbbec_camera::SetFilterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace orbbec_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af08a15d0d0ce8eb893e0f04f525118b";
  }

  static const char* value(const ::orbbec_camera::SetFilterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf08a15d0d0ce8ebULL;
  static const uint64_t static_value2 = 0x893e0f04f525118bULL;
};

template<class ContainerAllocator>
struct DataType< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orbbec_camera/SetFilterRequest";
  }

  static const char* value(const ::orbbec_camera::SetFilterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filter_name\n"
"bool filter_enable\n"
"float32[] filter_param\n"
;
  }

  static const char* value(const ::orbbec_camera::SetFilterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filter_name);
      stream.next(m.filter_enable);
      stream.next(m.filter_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFilterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orbbec_camera::SetFilterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orbbec_camera::SetFilterRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "filter_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.filter_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "filter_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.filter_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "filter_param: ";
    if (v.filter_param.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.filter_param.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.filter_param[i]);
    }
    if (v.filter_param.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORBBEC_CAMERA_MESSAGE_SETFILTERREQUEST_H
